### PR TITLE
Replace CREDITS.txt with link to GitHub insights

### LINKED ISSUE #442: Credits not shown in about box when installed with pip
When the client is installed with pip, either with ```pip3 install .``` or ```pip3 install cfclient```, the credits are not show in the about box.

This is likely due to the fact that the file ```CREDITS.txt``` is not copied in the distribution package by ```setup.py```.

### PR DESCRIPTION
**Pull request by jonasdn**
In order to avoid updating, distributing and installing the CREDITS.txt file we instead linkt to the GitHub contributor graphs.

New view:
credits

The "Used libraries" part is deleted because it was out-of-date and we do not have any nice tooling or process of keeping it up-to-date.

Closes #442

### CODE REVIEW

**Review by whoenig — COMMENTED** [review]
Is there any reason why the "Used libraries" part was deleted? I think that's fine, because it is not up-to-date/complete anyways, but perhaps we can document the reasoning for that in this PR.

**Comment by jonasdn** [comment]
> Is there any reason why the "Used libraries" part was deleted? I think that's fine, because it is not up-to-date/complete anyways, but perhaps we can document the reasoning for that in this PR.

I removed it because it was out-of-date, yes. I think maybe the `README.md` is the right place for that information, it needed at all. I can add the reasoning to the commit message.

**Comment by jonasdn** [comment]
Updated.

**Comment by whoenig** [comment]
Looks good to me - Thanks.

**Pull request merged**
