### PR TITLE
mine

### PR DESCRIPTION
**Pull request by Mitteau**

### CODE REVIEW

**Comment by Mitteau** [comment]
Implement a roll & pitch deadzone for the input device, parametrized according to the mapping json file. This improvement gives better stationary flight and progressive take off. Also add a json file for new xbox360 joystick.

**Comment by krichardsson** [comment]
Very nice, this is a great feature that is very useful!

However when I tested, it did not work out of the box since I do not have the "rp_dead_band" parameter in my settings. I get a 
```
Traceback (most recent call last):
  File "/Users/kristoffer/code/bitcraze/crazyflie-clients-python/src/cfclient/ui/main.py", line 738, in _inputconfig_selected
    self.joystickReader.set_input_map(device.name, selected_mapping)
  File "/Users/kristoffer/code/bitcraze/crazyflie-clients-python/src/cfclient/utils/input/__init__.py", line 307, in set_input_map
    self._rp_dead_band = settings["rp_dead_band"]
KeyError: 'rp_dead_band'
```
I suggest that you add a default value to make the change backwards compatible with configurations that users already have in their machines. You might want to take a look at the ```_translate_for_backwards_compatibility()``` function in the config_manager.py file for inspiration!

Thanks! 
Kristoffer

**Comment by krichardsson** [comment]
Thanks!

**Comment by Mitteau** [comment]
With pleasure!

**Pull request merged**
