### PR TITLE
updated install.mc

### PR DESCRIPTION
**Pull request by karlscholz**
tested it on several windows computers, Surfaces, HPs, Lenovos and all seem to had an issue with this pysdl2. I found a quick fix which I'm proposing here, but it'd be much better to include it in the dependencies.

### CODE REVIEW

**Comment by knmcguire** [comment]
Hi! So the proper way should be that the cfclient would install those already automatically due to this line: https://github.com/bitcraze/crazyflie-clients-python/blob/45ba7e6d43c9427f26157821bba9e27771e18982/setup.py#L78-L79 

Unfortunately, there seem to be something going on as this does not happen for a lot of windows users... as you can see in this issue: #592 

It would be better to figure out why it does not install it properly from the setup.py, but on the other hand it has been open out there for quite some time. 

@ataffanel or @krichardsson what are your thoughts on this?

**Comment by karlscholz** [comment]
I'm not very familiar with this topic. The better way would definitely be an automatic update, but since i started working with CF in may, this problem exists. Initially i thought it was only my pc. I'd at least insert a little note until this problem is fixed, because this prevents even the first getting started guide to be successful for pretty much every windows user.

**Comment by knmcguire** [comment]
Yeah.. it's been open too long. I've added some comments to the PR and then we can merge I think.

**Comment by karlscholz** [comment]
Also, just fyi, but i noticed that the website is not up to date with the github repo https://www.bitcraze.io/documentation/repository/crazyflie-firmware/master/development/openocd_gdb_debugging/ . If it's supposed to be like that ignore me :)

**Comment by knmcguire** [comment]
that might be because we haven't deployed the web for a while! We can't do it now but first thing next week!

**Comment by krichardsson** [comment]
Hi @karlscholz! 

I'm closing this PR since I hope the root problem has been fixed in #649. 
Please reopen this PR if you still have problems!

**Pull request closed without merging**
