### PR TITLE
snap: Make sure to always use the latest release tag

### PR DESCRIPTION
**Pull request by jonasdn**

### CODE REVIEW

**Review by ataffanel — COMMENTED** [review]
This builds master but set the version to the latest release might be a bit confusing.

The version we generate in setup.py currently is not conform with PEP-440 which is something we will want to change. What about coming-up with a format that would both match PEP-440 (so that we can use in setup.py) and work for the snap edge builds?

What about (ab)using the "local version label" to indicate that this is a git build with the git hash. Something like "2021.1+76-g9fd0440".

**Comment by jonasdn** [comment]
> This builds master but set the version to the latest release might be a bit confusing.
> 
> The version we generate in setup.py currently is not conform with PEP-440 which is something we will want to change. What about coming-up with a format that would both match PEP-440 (so that we can use in setup.py) and work for the snap edge builds?
> 
> What about (ab)using the "local version label" to indicate that this is a git build with the git hash. Something like "2021.1+76-g9fd0440"?

This suggestion does not build master, it builds the latest tag, the override-pull sees to that:
```
    override-pull: | # This override tells snapcraft to use latest release tag
      snapcraftctl pull
      last_tag="$(git describe --tags --abbrev=0 --match '[0-9]*.*')"
      git fetch
      git checkout "${last_tag}"
      snapcraftctl set-version "${last_tag}"
    source: https://github.com/bitcraze/crazyflie-clients-python.git
```

Is the strategy that the snap should always be a snapshot of master?
How does it work with building master of `crazyflie-clients-python` when there is a API or need for API in not yet published `crazyflie-lib-python`?

**Comment by ataffanel** [comment]
Those are good questions. We have tried over time to publish lib changes before using them in the client master in order to keep the client master in a workable order. So the strategy was that edge should follow master and we should never break master.

Recent development have broken this strategy though but I still think it is something we should aim for. I would suggest releasing the lib quickly and continuing to build edge on master, keeping master updated. I created #485 to track that problem, let see where we end-up there.

**Comment by ataffanel** [comment]
The snap is not working. Let's close this and review our build strategy when/if we get it working again.

**Pull request closed without merging**
