### PR TITLE
Added QualisysTab

### PR DESCRIPTION
**Pull request by mgejke**
Adds the Qualisys Tab to cfclient.
Add dependencies of two pure python packages, qtm & quamash.
quamash is used to create an eventloop that works with both Qt and asyncio

Will raise the required Python version to 3.5.2

### CODE REVIEW

**Comment by ataffanel** [comment]
Thanks for the PR!
We found one bug while testing the tab: the tab did not discover the QTM server if it is not running on the same machine, we had the client on a Linux machine and QTM on a Windows one on the same network. This should be either fixed or/and a field to set manually the IP of the QTM server should be added. I am planning to run more test later in the week to find out where the problem could be.

**Comment by mgejke** [comment]
Yeah, I heard that from Martin. (from what I can see, the tab had the same issues before my changes)
The issue is that we have to send out the QTM discovery packet on all interfaces, there's no built in solution to iterate those in Python, but I've tried with netifaces and with that it's easily solvable. But that adds another dependency.

The other option(in my opinion, less desirable) is to simply add an input box for the qtm ip.

Which path would you prefer?

**Comment by ataffanel** [comment]
I though this was the reason why the discovery was not working. Interfaces have quite random name in Linux nowadays.

A box with the IP would be good enough for me. Discovery is nice but when working with this kind of system we usually know about the IP or hostname (it is needed for crazyswarm for example).

**Comment by tobbeanton** [comment]
I've quickly tested the pull request and some initial feedback.
- For the position in the CF to work it needs to be flying using the kalman estimator. This could be changed by the Qualisys tab by setting the parameter stabilizer.estimator = 2.
- Pretty often the cfclient dies with a segmentation fault. We think this is because the Qualisys tab is modified outside the UI thread? This can only be done using signals and slots.
- On Ubuntu the position and orientation boxes are to small so the figures can not really be read.

**Comment by mgejke** [comment]
@tobbeanton 
1. I know nothing about the flight control part, where and how would I do that? 
``` cf.param.set_value('stabilizer.estimator', '2') ``` ?
2. Alright, works fine on windows. I guess it the flight_controller-thread... 
3. Could you supply a screenshot? Have nothing to test on here...

**Comment by mgejke** [comment]
Alright, all UI modification should be done on the UI thread now. Haven't got any ubuntu machines to test on here, so when you got the time... 

I think you said you could/had already solved the other two issues?

**Comment by mgejke** [comment]
@tobbeanton, @ataffanel 
Any news on this?

**Comment by krichardsson** [comment]
Sorry for the late reply!

We tested a bit and found some problems that must be fixed before we can merge. 

1. The IP address can not be set when the QTM dropdown is empty. On my machine no QTM server is found and if I enter the IP address manually nothing happens when I click connect. I suppose the if on line 740 must be extended.
1. The Kalman filter should be enabled in the Crazyflie. It is possible to switch estimator at run time by setting a parameter now as opposed to the re-compiling of the firmware that used to be required. Call `cf.param.set_value('stabilizer.estimator', '2')`
1. The UI is updated from `on_packet()' which is called from another thread (I think)
1. The UI is updated very frequently (on every packet from QTM). This and the previous point could for instance be solved by writing position data to memory and drive the UI updated with a timer.
1. On linux it seems as importing the Qualisys tab is preventing the plotter tab from working. We have no idea of why right now, we will continue to investigate this. Any input is welcome.

The first 4 should be fairly easy to fix while the 5th is a bit more fuzzy. Please let us know if you need any help.

- Kristoffer

**Comment by ataffanel** [comment]
We found a fix for 5. (not that we understand it), it was caused by the line [```_flight_path_set_model = pyqtSignal(QStandardItemModel)```](https://github.com/bitcraze/crazyflie-clients-python/pull/355/files#diff-0e40a8cf6d78b39b55dad3cea72b7508R173). If the line is changed to ```_flight_path_set_model = pyqtSignal(object)```, the tab still works fine but there is not problem anymore with pyQtGraph and the plotting tab!

**Comment by mgejke** [comment]
Think I've fixed all the issues. 
on_packet is not called from a thread, it's called asynchronously from the main ui-loop.

**Comment by krichardsson** [comment]
Merged! Thanks!

**Pull request merged**
