### PR TITLE
#359 detect decks both by onewire and params

### PR DESCRIPTION
**Pull request by NicksonYap**
Resolves:

https://github.com/bitcraze/crazyflie-clients-python/issues/359

Have tested for LED Ring only

Uses 'or' operator to detect decks so it's a fairly safe change

### CODE REVIEW

**Comment by krichardsson** [comment]
Nice improvement!

Could I suggest that you remove the one wire part and only keep the parameter solution?
The one wire check was simple to implement back in the days but the parameter solution you added is better and I think it would be clearer without the one wire code.

It might also solve the build problems on travis with lines that are too long :-)

**Comment by NicksonYap** [comment]
I originally intended to remove all `ow_search()`, however @ataffanel mentioned in: https://github.com/bitcraze/crazyflie-clients-python/issues/359#issuecomment-452744953 that there may a race condition where not all params are read 

I was only able to test for bcLedRing, where it enables the dropdown for LED setting
I'm not sure how the UI is rendered, but it seems fine for the dropdown

I wasn't able to test the others so it was safer to keep the `ow_search()`

**Comment by NicksonYap** [comment]
I gave the code a look again, it seems all `ow_search()` are for dropdowns, i suppose if it works for bcLedRing, it will work for others.

I'll resubmit the PR

**Comment by krichardsson** [comment]
Great!
Looks like you accidentally included the "Lighthouse quality" LED ring effect from the other PR as well :-)

**Comment by krichardsson** [comment]
@NicksonYap I did some cleaning when I merged this PR.
1. There was a mix of changes in the pull request and I reverted everything that was not related to detecting decks using parameters instead of OW memory.
1. When a parameter is read the value is returned as a string. I changed your cast to a bool into a cast to int to make it work.

I think the problems related to mixed content in the PR is related to you using master for the PR. By using separate feature branches for each pull request, as well as separating features into multiple pull requests, each containing one feature, simplifies the handling on our side. 

Never the less, thanks for the contribution!

**Pull request merged**
