### PR TITLE
Support Webots connection

### PR DESCRIPTION
**Pull request by simondlevy**
Works with https://github.com/bitcraze/crazyflie-simulation/pull/42

### CODE REVIEW

**Comment by knmcguire** [comment]
hi! there seems to be something wrong with the diffs so it's impossible to see what you have changed. Were the indention changed as well or something?

**Comment by simondlevy** [comment]
Weird ... I will close the pull request and attempt to figure out what went wrong.

**Comment by simondlevy** [comment]
Weird ... from my end, the diffs and merging look fine (see attached).  I'll try doing another PR, and if that doesn't work, I can try doing a PR for one file-change at a time (more work on your end, but should reveal what the problem is).
Screenshot from 2023-08-08 15-23-50

**Comment by knmcguire** [comment]
hi! please see my comment on the new PR, I think we should perhaps take a step back and make strategies first

**Pull request closed without merging**
