### PR TITLE
Add QScrollArea to support resizing the main window

### PR DESCRIPTION
**Pull request by fredg02**
Inspired by this forum request:
https://forum.bitcraze.io/viewtopic.php?f=11&t=2002

### CODE REVIEW

**Comment by ataffanel** [comment]
Nice Fred! I have 2 comments:
 - It would be nice to keep a default size bigger than the limit for the scroll bar to appear
 - Is it possible to make the scroll box invisible? Currently it is visible even when the window is big enough

**Comment by fredg02** [comment]
Hi Arnaud,
I will try to fix both issues.

**Comment by fredg02** [comment]
Both issues should be fixed now.

**Comment by ataffanel** [comment]
:+1: Looks good, the box is not visible anymore :).

For the size though it does not seems to work: the window is still too small for me. I am afraid this is dependent of the particular OS/WM/Font. There should be a way to calculate the size of all the widgets and set that as default. I will look a bit at it.

**Comment by fredg02** [comment]
OK. It works for me, but I will definitely try to fix it.

**Comment by ataffanel** [comment]
One way to test is in the new VM, by the way it comes that way:
client_in_vm

**Comment by krichardsson** [comment]
Hi @fredg02 !

I just want to check the status on this PR. 
We are trying to clean out PRs that are not active and this is a candidate as it has not been touched since June. Do you have any plans on fixing the last touches or should we close it for now and reopen it when you find time to work on it?

- Kristoffer

**Comment by mikezter** [comment]
Today i learned: The cfclient has a status bar :)

I agree, the default size should show everything, if enough space is availlable. On my 1280x800 screen, however, there just isn't enough vertical space. So in general i really like having the scrollbar.

I fiddled a bit in QtCreator and managed to give the window more height, but unfortunately i could not figure out how to calculate the size dynamically. Setting `MainWindow` and `centralwidget` to a height of 1000 will not trigger the scrollbar on startup. I'm still figuring out Qt Layouts, but i suspect that the apps layout needs an overhaul to allow Qt to dynamically resize the window based on user preferences like font size.

I was thinking about moving the "Auto Reconnect" and "Address" widgets in between "Scan" and "Battery" to save some vertical space.

**Comment by ataffanel** [comment]
Lets merge this and fix the window size somehow :-). Thanks fred!

**Comment by fredg02** [comment]
Sorry @krichardsson, I somehow missed your comment. Unfortunately I did not find a solution how the window can be resized dynamically.

**Pull request merged**
